#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#-----------------------------------Overrides for Hypervisor-----------------------------#
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
hardening_firewall_enabled: false                  # Proxmox has its own firewall + vmbr bridges; No touchy
hardening_autoupdate_apply: false                  # hypervisor updates are manual, deliberate events
hardening_ip_forward: 1                            # Override to prevent sysctl task from stopping ip forwarding