---
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#---------------------------------------Main task import---------------------------------#
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
- name: Configure SSH hardening
  import_tasks: ssh.yml
  tags: [ssh]

- name: Apply sysctl hardening
  import_tasks: sysctl.yml
  tags: [sysctl]

- name: Configure host firewall
  import_tasks: firewall.yml
  tags: [firewall]
  when: hardening_firewall_enabled | bool

- name: Configure unattended upgrades
  import_tasks: autoupdates.yml
  when: hardening_autoupdates_enabled | bool
  tags: [autoupdates]
