---
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#---------------------------------------Main task import---------------------------------#
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
- import_tasks: ssh.yml
  tags: [ssh]

- import_tasks: sysctl.yml
  tags: [sysctl]

- import_tasks: firewall.yml
  tags: [firewall]

- import_tasks: autoupdates.yml
  tags: [autoupdates]
