---
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#---------------------------------------Main task import---------------------------------#
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
- import_tasks: ssh.yml
  tags: [ssh]

- import_tasks: sysctl.yml
  tags: [sysctl]

- import_tasks: firewall.yml
  tags: [firewall]
  when: hardening_firewall_enabled | bool

- import_tasks: autoupdates.yml
  when: hardening_autoupdate_apply | bool or os_family == 'RedHat'
  tags: [autoupdates]
