---
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#-------------------------------------Hardening for SSH----------------------------------#
#=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  - name: Assert to make sure that hardening_desktop_user is set
    ansible.builtin.assert:
      that: 
      - hardening_desktop_user is defined
      - hardening_desktop_user | length > 0

  - name: Validation that directory exists with right permissions and creating it if it doesn't
    ansible.builtin.file:
      path: /etc/ssh/sshd_config.d/
      state: directory
      mode: 0755
    become: true

  - name: The copying of template file 
    ansible.builtin.template:
      src:  templates/00-hardening-ssh.conf.j2
      dest: /etc/ssh/sshd_config.d/00-hardening-ssh.conf
      validate: '/usr/sbin/sshd -t -f %s'
    become: true
    notify: restart sshd
    

  - name: Verification that sshd config works
    ansible.builtin.command:
      cmd: 'sshd -t'
    changed_when: false
    become: true
