---
# tasks file for roles/common
- name: Ensure ansible user exists with sudo privileges and SSH key
  become: yes
  tags: admin
  ansible.builtin.user:
    name: "ansible"
    append: true
    groups: "{{ admin_group }}"

- name: Add authorized ssh key to each host
  become: yes
  tags: admin
  ansible.posix.authorized_key:
    user: "ansible"
    key: "{{ ansible_user_ssh_key }}"

- name: Install EPEL repo (RedHat family)
  become: yes
  tags: packages
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat'  
      
- name: Update apt cache (Debian family)
  become: yes
  tags: packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'
      
- name: Update and Install essential packages
  become: yes
  tags: packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Configure chrony for time sync
  become: yes
  tags: ntp
  ansible.builtin.service:
    name: "{{ ntp_service_name }}"
    enabled: yes
    state: started
  when: ansible_facts['virtualization_type'] != 'lxc'

- name: Set proper hostname for each host
  become: yes
  tags: hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set passwordless sudo for ansible user
  become: yes
  tags: admin
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/20-ansible-user
    validate: visudo -cf %s

