---
# tasks file for roles/common
- name: Ensure ansible user exists with sudo privileges and SSH key
  become: true
  tags: admin
  ansible.builtin.user:
    name: "ansible"
    append: true
    groups: "{{ common_admin_group }}"

- name: Add authorized ssh key to each host
  become: true
  tags: admin
  ansible.posix.authorized_key:
    user: "ansible"
    key: "{{ ansible_user_ssh_key }}"

- name: Install EPEL repo (RedHat family)
  become: true
  tags: packages
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Update apt cache (Debian family)
  become: true
  tags: packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'

- name: Update and Install essential packages
  become: true
  tags: packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Configure chrony for time sync
  become: true
  tags: ntp
  ansible.builtin.service:
    name: "{{ common_ntp_service_name }}"
    enabled: true
    state: started
  when: ansible_facts['virtualization_type'] != 'lxc'

- name: Set proper hostname for each host
  become: true
  tags: hostname
  ansible.builtin.hostname:
    name: "{{ system_hostname | default(inventory_hostname) }}"

- name: Set passwordless sudo for ansible user
  become: true
  tags: admin
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD: ALL\n"
    dest: /etc/sudoers.d/20-ansible-user
    validate: visudo -cf %s

- name: Deploy ssh banner
  become: true
  tags: banner
  ansible.builtin.template:
    src: banner.j2
    dest: /etc/ssh/banner
  notify: Restart sshd

- name: Point sshd at banner
  become: true
  tags: banner
  ansible.builtin.template:
    src: 10-custom.conf.j2
    dest: /etc/ssh/sshd_config.d/10-custom.conf
    validate: '/usr/sbin/sshd -t -f %s'
  notify: Restart sshd
